server:
  port: 9191
spring:  application:    name: API-GATEWAY
  cloud:    gateway:      routes:      - id: STOCK-SECTOR
        uri: lb://STOCK-SECTOR
        predicates: Path=/mymarketplace/sector/**
      - id: STOCKS
        uri: lb://STOCKS
        predicates: Path=/mymarketplace/stock/**
      - id: LOGIN-SERVICE
        uri: lb://LOGIN-SERVICE
        predicates: Path=/mymarketplace/login/**  zipkin:
    base-url: http://localhost:9411/